# Generated by Django 5.1.1 on 2024-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_contentschedule_keyword_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentschedule',
            name='keyword_difficulty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentschedule',
            name='traffic_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
